services:
  db:
    image: postgres:16.2-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: redub_dev
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql:/var/lib/postgresql

  redub:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3030:3000'
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    secrets:
      - jwt_private
      - jwt_public
    entrypoint: sh -c "/src/scripts/init.sh"
    restart: always

secrets:
  jwt_private:
    file: ./secrets/private.key
  jwt_public:
    file: ./secrets/public.key