services:
  redub:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3030:3000'
    environment:
      DATABASE_URL: ${DATABASE_URL}
    secrets:
      - jwt_private
      - jwt_public
    entrypoint: sh -c "/src/scripts/init.sh"
    restart: always

secrets:
  jwt_private:
    file: ./secrets/private.key
  jwt_public:
    file: ./secrets/public.key